### PR TITLE
Upgrade ibc-go to 2.4.2

### PR DESCRIPTION
**Pull request by RusAkh**

### CODE REVIEW

**Comment by faddat** [comment]
Hi Ruslan, this is a state-breaking change because it moves from ibc-go v2 to ibc-go v3.

So now, basically it's a question of what the Likecoin team would like to do.  

If they want the changes to be (most likely, heh) non-breaking they can stay with v2 and you should use:

https://github.com/cosmos/ibc-go/releases/tag/v2.4.2

In fact, probably the best path looks like:

* upgrade to v2.4.2 now

**then**

* upgrade to v3.3.1 during a governance initiated software upgrade.

**Comment by RusAkh** [comment]
> Hi Ruslan, this is a state-breaking change because it moves from ibc-go v2 to ibc-go v3.
> 
> So now, basically it's a question of what the Likecoin team would like to do.
> 
> If they want the changes to be (most likely, heh) non-breaking they can stay with v2 and you should use:
> 
> https://github.com/cosmos/ibc-go/releases/tag/v2.4.2
> 
> In fact, probably the best path looks like:
> 
> * upgrade to v2.4.2 now
> 
> **then**
> 
> * upgrade to v3.3.1 during a governance initiated software upgrade.
got it, thank you @faddat

**Comment by williamchong** [comment]
Not sure if the patch is urgent, if yes I think we should go for 2.4.2 first
if not we might as well update to ibc v5 later together with an sdk upgrade
cc @nnkken

**Comment by williamchong** [comment]
(something wrong with my github UI that does not update comments)
yes I agree with @faddat , that a minor release with v2.4.2 is better (assume it doesn't break state)

**Comment by RusAkh** [comment]
@williamchong changed to abc 2.4.2

**Comment by williamchong** [comment]
Thanks for the contribution, I think we would also do a sdk minor upgrade later

**Pull request merged**
